// <auto-generated />
using DatabaseClassLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseClassLib.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230227060421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("DatabaseClassLib.Dataset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hashcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LabelsIndices")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("X1")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("X2")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Y1")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Y2")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ID");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("DatabaseClassLib.Img", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Hashcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Imgs");
                });
#pragma warning restore 612, 618
        }
    }
}
